translate_parms = {
    "higher": "Высшее",
    "not_required_or_not_specified": "Не требуется или не указано",
    "special_secondary": "Среднее профессиональное",
    "unfinished_higher": "Незаконченное высшее",
    "secondary": "Среднее",
    "bachelor": "Бакалавр",
    "master": "Магистр",
    "candidate": "Кандидат наук",
    "doctor": "Доктор наук",
    "employment_part": "Неполный рабочий день",
    "from_four_to_six_hours_in_a_day": "От 4 до 6 часов в день",
    "start_after_sixteen": "По вечерам",
    "employment_project": "Разовое задание",
    "only_saturday_and_sunday": "По выходным",
    "between1And3": "1-3 года",
    "noExperience": "Нет опыта",
    "between3And6": "3-6 лет",
    "moreThan6": "Более 6 лет",
    "fullDay": "Полный день",
    "shift": "Сменный график",
    "flyInFlyOut": "Вахтовый метод",
    "remote": "Удаленная работа",
    "flexible": "Гибкий график",
    "living_or_relocation": "Живут или готовы переехать в регион",
    "living": "Живут в регионе",
    "living_but_relocation": "Готовы уехать из региона",
    "relocation": "Не живут, но готовы переехать в регион",
    "male": "Мужчина",
    "female": "Женщина",
    "unknown": "Неизвестно",
    "not_looking_for_job": "Не ищет работу",
    "looking_for_offers": "Рассматривает предложения",
    "active_search": "Активно ищет работу",
    "has_job_offer": "Предложили работу, решает",
    "accepted_job_offer": "Вышел на новое место работы",
    "volunteer": "Волонтерство",
    "probation": "Стажировка",
    "project": "Проектная работа",
    "part": "Частичная занятость",
    "full": "Полная занятость",
    "Пропустить": "Пропустить",
    "20": "20",
    "40": "40",
    "0": "0"
}
reverse_translate_parms = {
    "Высшее": "higher",
    "Не требуется или не указано": "not_required_or_not_specified",
    "Среднее профессиональное": "special_secondary",
    "Незаконченное высшее": "unfinished_higher",
    "Среднее": "secondary",
    "Бакалавр": "bachelor",
    "Магистр": "master",
    "Кандидат наук": "candidate",
    "Доктор наук": "doctor",
    "Неполный рабочий день": "employment_part",
    "От 4 до 6 часов в день": "from_four_to_six_hours_in_a_day",
    "По вечерам": "start_after_sixteen",
    "Разовое задание": "employment_project",
    "По выходным": "only_saturday_and_sunday",
    "1-3 года": "between1And3",
    "Нет опыта": "noExperience",
    "3-6 лет": "between3And6",
    "Более 6 лет": "moreThan6",
    "Полный день": "fullDay",
    "Сменный график": "shift",
    "Вахтовый метод": "flyInFlyOut",
    "Удаленная работа": "remote",
    "Гибкий график": "flexible",
    "Живут или готовы переехать в регион": "living_or_relocation",
    "Живут в регионе": "living",
    "Готовы уехать из региона": "living_but_relocation",
    "Не живут, но готовы переехать в регион": "relocation",
    "Мужчина": "male",
    "Женщина": "female",
    "Неизвестно": "unknown",
    "Без статуса поиска": "unknown",
    "Не ищет работу": "not_looking_for_job",
    "Рассматривает предложения": "looking_for_offers",
    "Активно ищет работу": "active_search",
    "Предложили работу, решает": "has_job_offer",
    "Вышел на новое место работы": "accepted_job_offer",
    "Волонтерство": "volunteer",
    "Стажировка": "probation",
    "Проектная работа": "project",
    "Частичная занятость": "part",
    "Полная занятость": "full",
    "Пропустить": "Пропустить",
    "20": "20",
    "40": "40",
    "0": "0"
}